version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
  redis-backup:
    container_name: redis-backup
    image: redis:latest
    command: sh -c "sleep 60 && redis-cli -h redis-container -p 6379 save && mv /data/dump/dump.rdb /backup/redis-$(date '+%Y%m%d-%H%M%S').rdb && tar cf /backup/redis-$(date '+%Y%m%d-%H%M%S').tar -C /backup redis-$(date '+%Y%m%d-%H%M%S').rdb && rm -rf /backup/redis-$(date '+%Y%m%d-%H%M%S').rdb"
    volumes:
    - ./backup:/backup
    depends_on:
    - redis
    restart: always